version: "3.8"
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-stats-bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NODE_ENV=production
      - SKIP_AUTH=true
      - API_PORT=3000
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    networks:
      - poker-net

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: poker-frontend
    restart: unless-stopped
    ports:
      - "8080:80" # Фронтенд будет доступен на порту 8080
    depends_on:
      - bot
    networks:
      - poker-net

networks:
  poker-net:
    driver: bridge
