services:
  bot:
    build: .
    container_name: telegram-stats-bot
    restart: unless-stopped
    environment:
      - TELEGRAM_API_URL=${TELEGRAM_API_URL}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - ./data:/app/data
